# Generated by Django 4.0.6 on 2022-07-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
