# Generated by Django 4.0.6 on 2022-07-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='parentesco',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
