# Generated by Django 4.0.6 on 2022-08-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_parentesco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='product',
        ),
    ]
