# Generated by Django 4.0.6 on 2022-08-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_birth',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
