# Generated by Django 4.0.6 on 2022-08-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('body', models.CharField(max_length=1200)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('author', models.CharField(max_length=40)),
            ],
        ),
    ]
