# Generated by Django 4.1 on 2022-09-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_image_alter_character_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='clase',
            field=models.CharField(max_length=50),
        ),
    ]
