# Generated by Django 4.0.6 on 2022-09-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='address',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='favorite_class',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
